### ISSUE TITLE
Cannot identify dialect of sql.str/simplify.str/heuristics.str/wp.str

### ISSUE THREAD

**Issue by seyyedshah** [Booster2/Booster2#3]
in the new use-spoofax-2.0 branch, most of the changes from http://www.metaborg.org/en/latest/source/release/migrate/2.0.0.html are complete but some of the transformations can't be parsed so an editor is not created - spoofax complains about identifying the language, something needs to be done to point it in the right direction. The .meta files may have changed or have been deprecated.

**Comment by edwardcrichton** [comment]
@seyyedshah Is the resolution of this accompanied by a commit?

**Comment by seyyedshah** [comment]
@edwardcrichton, yep it was @dcharkes who fixed this one, as it seems the embedded syntax in the transformations is no longer build in eclipse, so there's a shell script to do this, added in 5dfe5c98f6c2af33fed5ce789e67e38832b03908

**Comment by dcharkes** [comment]
(Copied from the Slack conversation with @seyyedshah)

There are a number of non backwards compatible changes in 2.0:

1. Mix-syntax is not compiled in Eclipse anymore, this is done on the command-line now (5dfe5c98f6c2af33fed5ce789e67e38832b03908)
2. The main stratego file should be lower cased (c2995f7ba064f689104cd4bd81ad8333dbb58e3e and de9d02dde81380a90a7dc965c327d53b1eac4de9)
3. The paths of generated files changed, so I fixed the stratego imports (b4c91d0701759d25331f81497bc46c59d81e40d4 and 5afbbe7c4e240b92bfe57855061b4ff3e039a8c7)

The command-line generator for mix-syntax is in `Booster2.5/gen-parse-table.sh` (OS X shell script).
And the command-line tools can be installed on OS X with `brew tap metaborg/metaborg && brew update && brew install strategoxt20 && str '!"Hello, world!"'`.
On Linux this should be similar.

**Comment by seyyedshah** [comment]
The metaborg brew tap needs a small edit and works fine on linux using https://github.com/Linuxbrew/linuxbrew , the change is in the strategoxt20.rb , to point to the latest `version` and `md5` (2.0.0-20160617.092655-208 / bf7e6bc11da7bbce5c1c1d74bf1369bb03bda9a02dbe058433d9295265416481  taken from [here](http://artifacts.metaborg.org/service/local/repositories/snapshots/content/org/metaborg/strategoxt-distrib/2.0.0-SNAPSHOT/)
